@host = http://localhost:3000/api

### @name createUser
POST {{host}}/users
Content-Type: application/json

{
    "email": "francis@example.dev",
    "username": "francis",
    "password": "123456"
}

### @name userLogin
POST {{host}}/login
Content-Type: application/json

{
    "email": "francis@example.dev",
    "password": "123456"
}
